### ISSUE TITLE
It takes two taps on mobile...

### ISSUE THREAD

**Issue by OakBehringer** [trmcnvn/ember-star-rating#17]
First interaction with star rating takes two taps on mobile (safari, iOS) to get the onclick event to fire. It happens in your own demo:

https://www.vevix.net/ember-star-rating/ 

Removing the mouseMove event from the component "fixes" it - but then you don't get the desired mouseover effect on desktop. 

Only affects the FIRST mobile tap. 

Step 1: load your demo in safari
Step 2: tap a star in the Editable rating demo
-- star rating visually updates 
-- click event does NOT fire
Step 3: tap Editable rating demo again
-- star rating visually updates 
-- click event DOES fire
Step 4: tap again
-- star rating visually updates 
-- click event DOES fire

It's only in step 2, the first tap, that it fails

**Comment by OakBehringer** [comment]
http://sitr.us/2011/07/28/how-mobile-safari-emulates-mouse-events.html

https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent

**Comment by OakBehringer** [comment]
```
touchStart(event) {
  this._render(event);
},

touchMove(event) {
  this._render(event);
},

touchEnd(event) {
  event.preventDefault();
  const rating = this._update(event);
  this._render(event);
  get(this, 'onClick')(rating || 0);
},
```
Add this - fixes the problem. Mouse events will never be fired b/c of preventDefault() (see above link with event ordering). touchMove keeps it updating the UI if you drag your thumb across. touchEnd makes the changes after any dragging thumb stuff. The rest should be self-explanatory what I've done. 

Then, change _getTarget() to this:

```
_getTarget(x) {
  const numStars = get(this, 'numStars');
  let numStarsFilled = (numStars * (x - this.$().offset().left) / this.$().width() + 0.5);

  if (numStarsFilled > numStars) {
    numStarsFilled = numStars;
  }

  if (get(this, 'useHalfStars')) {
    return numStarsFilled;
  }
  return Math.ceil(numStarsFilled - 0.5);
},
```

I have added a sanity check for numStarsFilled, so that dragging beyond the number of stars, during a touch event, will prevent the value exceeding the number of stars. In other words, without this, the touchEnd event could be fired (thumb lifted up) when the thumb is outside the component, and a five star rating component could return a rating of 8 (or other value higher than 5). 

No time for a PR right now.

**Comment by OakBehringer** [comment]
PR created. 

https://github.com/trmcnvn/ember-star-rating/pull/18

**Comment by trmcnvn** [comment]
Thanks 👍
