### ISSUE TITLE
Doesn't work on Chrome-based mobile

### ISSUE THREAD

**Issue by lougreenwood** [trmcnvn/ember-star-rating#21]
It seems that v1.4.0 broke the add-on when used in chrome-based mobile browsers.

This can be verified by visiting the demo app (https://www.vevix.net/ember-star-rating/) in Chrome and enabling responsive design mode.

When in responsive design mode, clicks will set the stars to a value of 0.

I have also verified this on Android devices.

After some digging it seems that the bug is around this line of code:
https://github.com/trmcnvn/ember-star-rating/blob/master/addon/components/star-rating.js#L94

Where the problem seems to be that the `event.pageX` is undefined for `touch*` events on chrome-based mobile devices/views.

I've checked and this bug is present in version 1.4.0 and upwards.

**Comment by lougreenwood** [comment]
ccing @OakBehringer incase they have any ideas since the addition of touch events was theirs

**Comment by cmaturana** [comment]
They found a solution? I still have the same problem and can be understood in the Chrome browser simulating a mobile device

**Comment by trmcnvn** [comment]
@cmaturana Are you on the latest version (2.0.3)?

The preview site was outdated. I just updated it now and it seems Chrome is working for me.

**Comment by cmaturana** [comment]
I am occupying version 2.0.3, and I continue with the problem in chrome and webview of my mobile phone. When I occupy the chrome browser in normal mode and pass the cursor over it marks them, but when it is in phone mode it does not allow to easily select, and if I select 1 the others are deleted (I have more than one rating item)
My chrome version is 74.0.3729.169

**Comment by trmcnvn** [comment]
Odd, I'm seeing no issues on Chrome or Firefox on Desktop and Mobile.

Would you be able to reproduce this behaviour on https://ember-twiddle.com by chance?

**Comment by lougreenwood** [comment]
Preview site also works for me on Chrome 75.0.3770.80 - Mac OS
