### ISSUE TITLE
What to pass with the action ?

### ISSUE THREAD

**Issue by langereissilvio** [trmcnvn/ember-star-rating#5]
Depending on the answer I'll get, I will feel incredibly stupid, or not...
What param do I pass with the action ? User clicks on 2.5 stars, where is that 2.5 stored ? The ReadMe never specifies this, unless I'm overlooking something, see first line I wrote ! ;)

{{star-rating
         numStars=5
         readOnly=false
         baseColor="#d1cccc"
         fillColor="#f79902"
         onClick=(action 'setRating'  **...?** )
}}

**Comment by trmcnvn** [comment]
The addon itself will pass the rating value to your defined action.

Example:

```javascript
onClick=(action 'setRating')
```

```javascript
actions: {
  setRating(rating) {
    console.log(rating); // # => 2.5
  }
}
```

**Comment by langereissilvio** [comment]
Thanks, just implemented it, no further issues, good and clean star rating addon. I'll close this down now. :)
